version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ngrok:
  #   image: wernight/ngrok:alpine
  #   ports:
  #     - "4040:4040"
  #   environment:
  #     - NGROK_AUTH=${NGROK_AUTH_TOKEN}
  #     - NGROK_PROTOCOL=http
  #     - NGROK_PORT=app:3000
  #   depends_on:
  #     - app

volumes:
  postgres_data: